---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Compare SSF params with RRV

Here we compare SSF coefficients with RRV scores.

## Load libraries and prepare files

```{r}
# libs for data
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(stringr)

# libs for messages
library(glue)

# library for SSF data
library(amt)

# plotting libs
library(ggplot2)
library(colorspace)
```

Load data from saved `Rds` object, and RRV data.

```{r}
# add ssf data
load("data/results/data_fitted_ssfs.Rds")

# load rrv data
rrv <- read_csv("data/results/data_daily_rrv.csv")
```

## SSF parameters

```{r}
# filter for bad fits
ssfs <- filter(
  ssfs,
  !map_lgl(
    ssf, is.null
  )
)

# select track identifiers
ssf_params <- select(
  ssfs,
  -matches("ssf")
)

# select model parameter for ndvi preference
ssf_params <- mutate(
  ssf_params,
  coefs = map(ssfs$ssf, function(l) {
    tryCatch(
      expr = {
        broom::tidy(
          l$model
        )
      },
      error = function(e) {
        return(NULL)
      }
    )
  }),
  shape = map_dbl(ssfs$ssf, function(l) {
    l$sl_$params$shape
  })
)

# unnest
ssf_params <- unnest(ssf_params, cols = coefs)

# get exp coefs
ssf_params = mutate(
  ssf_params,
  exp_coef = exp(estimate)
)

rm(ssfs); gc()
```

## Link SSF coefficients and RRV

```{r}
# make rrv date as date
rrv <- mutate(
  rrv,
  date = lubridate::date(date)
)

# edit date class to characters
rrv$date = as.character(rrv$date)
ssf_params$date = as.character(ssf_params$date)

# link ssf params and rrv
ssf_params <- left_join(
  ssf_params,
  rrv
)
```

## Correct SL in LC classes

```{r}
# filter coefficients
data <- filter(
  ssf_params,
  treat != "LongPeriod",
  !is.na(estimate)
)

# get sl coefficient for all models
data <- data %>%
  group_by(
    TAG, date, sp, treat
  ) %>%
  mutate(
    sl_coef = estimate[term == "log_sl"]
  )

# get corrected SL for each landcover
data <- ungroup(data)
data <-
  mutate(
    data,
    estimate_corrected = case_when(
      str_detect(term, "sl:") ~ exp_coef + shape + sl_coef,
      str_detect(term, "log_sl") ~ exp_coef + shape,
      TRUE ~ estimate
    )
  )
```


```{r}
filter(
  data, sp != "Hirundo", 
  treat != "NonMoulting", 
  term != "log_sl",
  p.value <= 0.05
) |> 
ggplot() +
  geom_jitter(
    aes(
      rrv_calc, estimate_corrected,
      col = sp
    ),
    # shape = 1,
    show.legend = T,
    size = 2
  ) +
  geom_smooth(
    aes(
      rrv_calc, estimate_corrected,
      col = sp
    ),
    # shape = 1,
    method = "glm",
    show.legend = T
  ) +
  # geom_smooth(
  #   # data = filter(data, p.value < 0.05),
  #   aes(
  #     rrv_calc, estimate_corrected,
  #     col = treat
  #   ),
  #   show.legend = T,
  #   se = F,
  #   method = "glm"
  # )+
  scale_colour_viridis_d(
    option = "H",
    # direction = -1,
    begin = 0.2,
    end = 0.8
  ) +
  scale_alpha_manual(
    values = c(0.5, 1),
    guide = F
  ) +
  scale_x_continuous(
    # limits = c(1, 15)
    # trans = ggallin::ssqrt_trans
  ) +
  scale_y_continuous(
    # limits = c(1, NA)
    trans = ggallin::pseudolog10_trans
  ) +
  facet_grid(
    sp~term, 
    scales = "free_y"
  ) +
  theme_test()+
  theme(
    legend.position = "top"
  ) +
  labs(
    x = "Calculated RRV",
    # y = "Relative Selection Strength",
    shape = "Sp.",
    # col = "p < 0.05", 
    alpha = NULL
  )
```

## Relative Selection Strengths

```{r}
# prepare relative selection
relative_selection = data |> 
  select(
    TAG, sp, date, term, exp_coef,
    treat, rrv_calc
  ) |> 
  filter(
    term != "log_sl"
  )

# |> 
  # pivot_wider(
  #   id_cols = c("TAG", "sp", "date", "treat", "rrv_calc"),
  #   names_from = "term",
  #   values_from = "estimate_corrected"
  # )

# scale selection within daily tracks and 
relsel = relative_selection |> 
  group_by(
    TAG, sp, date, rrv_calc
  ) |> 
  mutate(
    scaled_estimate = exp_coef / sum(abs(exp_coef))
  )
```

```{r}
a = relsel |> 
  filter(
    sp != "Hirundo",
    term != "log_sl"
  ) |> 
  pivot_wider(
    id_cols = c("TAG", "sp", "date", "treat"),
    values_from = "scaled_estimate",
    names_from = "term"
  )

ggplot(a)+
  geom_jitter(
    aes(
      ndvi, vis, 
      col = treat
    )
  )+
  scale_y_continuous(
    trans = ggallin::pseudolog10_trans
  )

  geom_smooth(
    aes(
      rrv_calc, scaled_estimate,
      col = treat
    ),
    method = "glm",
    se = F
  )+
  facet_grid(term~sp)
```

