---
editor_options: 
  chunk_output_type: console
---

```{r}
library(sf)
library(terra)
library(data.table)
```

```{r}
# read patches
patches = st_read("data/spatial/data_patch_spatials.gpkg")
st_crs(patches) = 2039
```

## NDVI

```{r}
# read ndvi
ndvi = rast("data/rasters/raster_hula_ndvi.tif")
ndvi = terra::project(
  ndvi,
  st_crs(2039)$proj4string
)

writeRaster(
  ndvi,
  filename = "data/rasters/raster_hula_ndvi_2039.tif"
)
```

```{r}
ndvi = rast("data/rasters/raster_hula_ndvi_2039.tif")

# sample mean ndvi over raster
ndvi_sample = terra::extract(
  ndvi,
  vect(patches),
  fun=mean
)
```

```{r}
# rm(ndvi); gc()
```

## Visibility

```{r}
# read visibility at 1m res
vis = rast("data/rasters/raster_hula_visibility.tif")
```

```{r}
# sample mean visibility
vis_sample = terra::extract(
  vis,
  vect(patches),
  fun = mean
)
```

```{r}
patches$ndvi = ndvi_sample$ndvi
patches$vis = vis_sample$raster_hula_visibility

patches = st_drop_geometry(
  patches
)
patches = as.data.table(patches)

# save
fwrite(
  patches,
  file = "data/results/data_patch_cov_ppa.csv"
)
```

## Sample NDVI and visibility

```{r}
ext = ext(vis)
ext = st_bbox(c(ext[1], ext[2], ext[3], ext[4])) |> 
  st_as_sfc() |> 
  `st_crs<-`(2039) |> 
  st_sample(10000)

# ndvi sample
ndvi_rand = terra::extract(ndvi, vect(ext))
vis_rand = terra::extract(vis, vect(ext))

env_rand = merge(ndvi_rand, vis_rand)
setDT(env_rand)
setnames(env_rand, "raster_hula_visibility", "vis")

# save
fwrite(
  env_rand,
  file = "data/results/env_rand_values.csv"
)
```

