---
editor_options: 
  chunk_output_type: console
---

```{r}
library(sf)
library(terra)
library(data.table)

library(ggplot2)
library(colorspace)
```

```{r}
# load data
mcp = st_read("data/spatial/hula_lc_vector")
ndvi = rast("data/rasters/raster_hula_ndvi_2039.tif")
vis = rast("data/rasters/raster_hula_visibility.tif")
```

```{r}
# make samples
samples = st_sample(
  mcp,
  size = 10000,
  type = "hexagonal"
)
```

```{r}
# extract data at samples
vis_samp = extract(
  vis,
  vect(samples)
)
setDT(vis_samp)

ndvi_samp = extract(
  ndvi,
  vect(samples)
)
setDT(ndvi_samp)

# lc samples
lc_samp = extract(
  vect(
    dplyr::select(mcp, Name)
  ),
  vect(samples)
)
setDT(lc_samp)

# merge data
env_data = merge(vis_samp, ndvi_samp)
env_data = merge(env_data, lc_samp, by.x = "ID", by.y = "id.x")

# filter for valid values
env_data = env_data[!is.nan(raster_hula_visibility)]
env_data = setnames(env_data[, !("ID")], c("vis", "ndvi", "lc"))
```

```{r}
# landcover classifications
# B = settlement
# C = canal
# O = agriculture/open
# R = reedbeds
# T = trees
# W = water

env_data = env_data[!lc %in% c("C", "W")]
```

```{r}
# run glm
env_data$lc = factor(
  env_data$lc,
  levels = c("T", "R", "B", "O")
)

mod = glm(
  vis ~ ndvi*lc,
  data = env_data
)

model_summary = summary(mod)

writeLines(
  capture.output(model_summary),
  con = "data/results/model_coefs_vis_ndvi.txt"
)

mod_plot_data = sjPlot::get_model_data(mod, type = "int")
```

```{r}
# change group name
setDT(mod_plot_data)
setnames(mod_plot_data, "group", "lc")
mod_plot_data$lc_agro = mod_plot_data$lc == "O"
env_data$lc_agro = env_data$lc == "O"

# save env data
fwrite(
  env_data,
  "data/results/data_vis_ndvi.csv"
)

# save mod data
fwrite(
  mod_plot_data,
  "data/results/model_vis_ndvi_plot_data.csv"
)
```


```{r}
fig_vis_ndvi = 
  ggplot(
  env_data,
  aes(
    ndvi, vis
  )
)+
  geom_bin2d(
    aes(
      fill = ..density..
    ),
    binwidth = c(0.05, 0.05)
  )+
  geom_pointrange(
    data = mod_plot_data,
    aes(
      x, predicted,
      ymin = conf.low,
      ymax = conf.high,
      col = lc,
      shape = lc
    ),
    position = position_dodge(
      width = 0.1
    )
  )+
  scale_colour_discrete_qualitative(
    l1 = 40,
    labels = c("Orchards", "Reedbeds", "Settlements", "Crops")
  )+
  scale_shape(
    labels = c("Orchards", "Reedbeds", "Settlements", "Crops")
  )+
  scale_fill_continuous_sequential(
    palette = "Heat 2",
    guide = "none"
  )+
  facet_wrap(
    ~lc_agro,
    scales = "free",
    labeller = labeller(
      lc_agro = c(
        "TRUE" = "Crop fields & open areas",
        "FALSE" = "Orchards, reedbeds, settlements"
      )
    ),
    ncol = 1
  )+
  coord_cartesian(
    ylim = c(0, 1)
  )+
  theme_test(
    base_size = 8,
    base_family = "Arial"
  )+
  theme(
    legend.position = "bottom",
    legend.margin = margin(rep(0, 4)),
    legend.key.height = unit(4, "mm"),
    legend.key.width = unit(5, "mm"),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "bold"
    )
  )+
  guides(
    colour = guide_legend(
      nrow = 2
    ),
    shape = guide_legend(
      nrow = 2
    )
  )+
  labs(
    x = "NDVI",
    y = "Visibility index",
    colour = NULL,
    shape = NULL
  )

ggsave(
  fig_vis_ndvi,
  filename = "figures/fig_vis_ndvi.png",
  height = 87,
  width = 52, units = "mm"
)
```

