---
editor_options: 
  chunk_output_type: console
---

# Visualise data cleaning

```{r}
library(data.table)
library(ggplot2)
library(patchwork)
library(ggspatial)
```

```{r}
# read file names
files <- list.files("data/processed/data_preprocessed",
  full.names = TRUE
)

# raw data
files_raw = list.files(
  "data/processed/data_id",
  full.names = TRUE
)

# read treatment data
treat_data = fread("data/results/data_tracking_metrics_rrv.csv")
```

```{r}
for (file in files) {
  # read processed data
  data = fread(file)
  data = merge(data, treat_data[, c("TAG", "treat", "RRV")], all.x = T)
  # get tag
  tag = unique(data$TAG)
  treat = unique(data$treat)
  sp = unique(data$sp)
  
  xlim = range(data$X)
  ylim = range(data$Y)
  
  message(
    glue::glue(
      "sp = {sp} tag = {tag} treat = {treat}"
    )
  )
  
  # get raw data
  file_raw = files_raw[grep(tag, files_raw)]
  # file_raw = file_raw[grep(treat, file_raw)][1]
  
  message(
    glue::glue(
      "file-raw = {file_raw}"
    )
  )
  
  data_raw = fread(file_raw)
  data_raw[, time := as.POSIXct(as.numeric(TIME) / 1000, 
                                tz = "Asia/Jerusalem", origin = "1970-01-01")]
  data_raw[, date := lubridate::date(time)]
  
  # assert correct tag
  assertthat::assert_that(
    tag == unique(data_raw$TAG)
  )
  
  p =
    ggplot(
    data = data,
    aes(X, Y)
  )+
    geom_point(
      data = data_raw,
      col = "grey",
      alpha = 0.2
    )+
    geom_path(
      col = "grey20",
      size = 0.1,
      aes(group = interaction(date, hour))
    )+
    geom_point(
      # shape = 1,
      # col = "seagreen",
      aes(
        col = factor(date)
      ),
      alpha = 0.3
    )+
    colorspace::scale_colour_discrete_sequential(
      palette = "Batlow"
    )+
    ggspatial::annotation_scale(
      style = "ticks",
      width_hint = 0.05,
      location = "br"
    )+
    coord_sf(
      crs = 2039,
      xlim = xlim,
      ylim = ylim
    )+
    ggthemes::theme_map()+
    theme(
      legend.key = element_rect(
        fill = "transparent",
        colour = NA
      ),
      legend.background = element_rect(
        fill = "transparent",
        colour = NA
      ),
      plot.background = element_rect(
        fill = "white"
      )
    )+
    labs(
      title = glue::glue("sp: {sp} tag: {tag}
                         treat: {treat}
                         "),
      col = "date"
    )
  
  ggsave(
    p,
    filename = glue::glue("figures/figures_preprocessing/fig_\\
                          {sp}_{tag}_{treat}.png"),
    height = 9,
    width = 16
  )
  
}
```

