---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Parameterising the residence patch method

## Load libraries and prepare files

```{r}
# libs for data
library(data.table)
library(lubridate)

# library for atlas data
library(atlastools)

# plotting
library(ggplot2)
library(ggspatial)
library(colorspace)
```

List the files.

```{r}
files <- list.files("data/processed/data_preprocessed",
  full.names = T
)
```


```{r}
# load data from file
data <- fread(files[30])
```

### Prepare data

```{r}
df <- data[, c("X", "Y", "time", "TAG", "date")]
df[, time := (
  as.POSIXct(time, origin = "1970-01-01", tz = "Asia/Jerusalem")
)]
setnames(df, old = "TAG", "id")

# get speeds and angles
df[, c("speed", "angle") := list(
  atl_get_speed(df, x = "X", y = "Y"),
  atl_turning_angle(df, x = "X", y = "Y")
)]

# fill NAs and NANs
df$angle <- nafill(df$angle, fill = 0)

# smooth speed
df[, speed := runmed(speed, k = 3)]

# quantile
speed_limit = quantile(df$speed, probs = 0.9)
```

### Check transit

```{r}
ggplot(df) +
  geom_path(
    aes(X, Y),
    col = "grey",
    size = 0.1
  ) +
  geom_point(
    aes(
      X, Y,
      col = speed,
      shape = speed <= 1
    )
  ) +
  scale_colour_continuous_sequential(
    palette = "Blues",
    trans = "sqrt",
    limits = c(0, speed_limit),
    na.value = "red"
  ) +
  facet_wrap(~date) +
  ggspatial::annotation_scale() +
  ggthemes::theme_map()
```

## Residence patch by day

```{r}
# remove transit
df <- df[speed < speed_limit / 2, ]

# split by date
df <- split(df, by = "date")

# apply res patch method
patches <- lapply(df, function(d) {
  d_ = copy(d)
  d_ <- d[, c("X", "Y", "id", "time")]
  setnames(d_, old = c("X", "Y"), new = c("x", "y"))

  atl_res_patch(
    data = d_,
    buffer_radius = 25, 
    lim_spat_indep = 100, 
    lim_time_indep = 30,
    min_fixes = 9
  )
})

# get patch summary
patch_summary <- lapply(patches, atl_patch_summary, which_data = "summary")

# patch points
patch_points <- lapply(patches, atl_patch_summary, which_data = "points")

# patch spatial
patch_spatial = lapply(
  patches, atl_patch_summary, 
  which_data = "spatial", buffer_radius = 25
)
```

## Visualise residence patches

### Patch summary

```{r}
patch_summary <- Map(function(data, names) {
  data$date <- names
  data$hour <- hour(as.POSIXct(data$time_start,
    origin = "1970-01-01",
    tz = "Asia/Jerusalem"
  ))
  data
}, patch_summary, names(patch_summary))

patch_summary <- rbindlist(patch_summary)
```

```{r}
ggplot(patch_summary)+
  geom_path(
    aes(
      x_median, y_median,
      col = as.factor(date),
      group = date
    )
  )+
  geom_point(
    aes(
      x_median, y_median,
      size = duration / 60,
      fill = as.factor(date)
    ),
    shape = 21
  )+
  facet_wrap(
    ~date
  )
```

### Patch points

```{r}
patch_points <- Map(function(data, names) {
  data$date <- names
  data
}, patch_points, names(patch_points))

patch_points <- rbindlist(patch_points)
```

```{r}
ggplot(patch_points)+
  geom_path(
    aes(
      x, y,
      col = as.factor(patch),
      group = interaction(date, patch)
    )
  )+
  geom_point(
    aes(
      x, y,
      fill = as.factor(patch)
    ),
    shape = 21
  )+
  facet_wrap(
    ~date
  )+
  ggspatial::annotation_scale() +
  ggthemes::theme_map()
```

### Patch spatials

```{r}
# id patch spatials
patch_spatial <- Map(function(data, names) {
  data$date <- names
  data
}, patch_spatial, names(patch_spatial))

patch_spatial <- rbindlist(patch_spatial)
patch_spatial = sf::st_as_sf(patch_spatial, sf_column_name = "polygons")
```

```{r}
ggplot() +
  # geom_path(
  #   aes(x_median, y_median,
  #     group = date
  #   ),
  #   lty = 1,
  #   size = 0.5
  # ) +
  geom_point(
    data = patch_points,
    aes(x, y),
    alpha = 0.1
  ) +
  geom_sf(
    data = patch_spatial,
    aes(fill = patch),
    alpha = 0.5
  )+
  geom_text(
    data = patch_summary,
    aes(x_median, y_median,
        label = patch)
  )+
  scale_size(range = c(3, 8)) +
  scale_colour_viridis_c(
    option = "H"
  ) +
  scale_fill_viridis_c(
    option = "H"
  ) +
  facet_wrap(~date) +
  ggspatial::annotation_scale(style = "ticks")
```
