---
editor_options: 
  chunk_output_type: console
---

# Mapping tracks

## Load libraries and prepare files

```{r}
# libs for data
library(data.table)
library(lubridate)

# library for atlas data
library(atlastools)

# plotting
library(ggplot2)
library(ggspatial)
library(colorspace)
library(scico)
```

```{r}
# load data from file
data <- fread("data/processed/data_for_analysis.csv")

# add date and hour of day
data[, c("date", "hour") := list(
  lubridate::date(as.POSIXct(time, origin = "1970-01-01", tz = "Asia/Jerusalem")),
  lubridate::hour(as.POSIXct(time, origin = "1970-01-01", tz = "Asia/Jerusalem"))
)]

# levels
data$treat <- factor(data$treat,
  levels = c("NonMoulting", "Moulting", "Manipulated")
)

# remove swallows and long term sparrows
data <- data[sp != "Hirundo" & treat != "LongPeriod"]
```

## Plot single species positions

```{r}
data <- split(data, by = "sp")

lapply(data, function(df) {
  species <- unique(df$sp)
  # plot and check
  fig_positions <-
    ggplot() +
    geom_path(
      data = df,
      aes(x, y, group = interaction(TAG_ID, date)),
      col = "grey",
      alpha = 0.3,
      size = 0.3
    ) +
    geom_point(
      data = df,
      aes(x, y, colour = treat),
      alpha = 0.2
    ) +
    scale_colour_discrete_qualitative(
      palette = "Harmonic",
      l1 = 50, h1 = 50,
      rev = T,
      name = "Wing condition",
      labels = c("Non moulting", "Moulting", "Manipulated")
    ) +
    ggthemes::theme_map() +
    theme(
      plot.background = element_rect(
        fill = "white",
        colour = NA
      )
    ) +
    ggspatial::annotation_scale(location = "tl", style = "ticks") +
    coord_sf(
      crs = 2039,
      xlim = range(df$x),
      ylim = range(df$y)
    ) +
    guides(
      colour = guide_legend(
        override.aes = list(
          alpha = 1, size = 3, shape = 19
        )
      )
    )

  # save
  ggsave(
    plot = fig_positions,
    filename = glue::glue("figures/fig_positions_{species}.png"),
    height = 12, width = 12
  )
})
```
