---
editor_options: 
  chunk_output_type: console
---

# Exploratory data analysis: Temporal Heatmap

## Load libraries

```{r}
# libs for data
library(data.table)
library(glue)

# libs for plotting
library(ggplot2)
library(patchwork)
```

## Load data

```{r}
# load saved data
data <- fread("data/results/data_daily_fixes.csv")

# set factor order
data$treat <- factor(data$treat,
  levels = c(
    "Moulting", "NonMoulting",
    "Manipulated", "LongPeriod"
  )
)
```

## Make heatmap of daily fixes

```{r}
# make heatmap of daily fixes
# split data by species
data <- split(data, by = "sp")

# heatmap of daily fixes
fig_daily_fixes <-
  Map(function(df, name) {
    # do ggplot
    ggplot(df) +
      geom_tile(
        aes(
          x = day, y = factor(TAG_ID),
          fill = nfixes
        )
      ) +
      scale_fill_viridis_c(
        option = "C", direction = 1,
        labels = function(x) {
          scales::comma(x, accuracy = 1, scale = 1e-3, suffix = "K")
        },
        limits = c(0, 40e3)
      ) +
      scale_x_date(
        limits = as.Date(c("2016-05-31", "2016-12-31"))
      ) +
      facet_wrap(~treat) +
      theme(
        axis.text.y = element_blank()
      ) +
      labs(
        x = "Day", y = "Tags",
        fill = "# Fixes / day",
        title = glue("Heatmap daily fixes: {name}")
      )
  }, data, names(data))

# wrap
fig_daily_fixes <-
  wrap_plots(fig_daily_fixes) +
    plot_layout(
      guides = "collect"
    ) &
    plot_annotation(
      tag_levels = "A"
    )

# save figure
ggsave(
  fig_daily_fixes,
  filename = "figures/fig_daily_fixes.png"
)
```

## Select data by daily samples sizes

WIP ---  return to this after mapping data.
