---
editor_options: 
  chunk_output_type: console
---

# Select tracking data by day

Here we load the pre-processed data, which has been smoothed and thinned to 20 seconds interval.

## Load libraries and prepare files

```{r}
# libs for data
library(data.table)
library(lubridate)

# for eda
library(ggplot2)
```

Prepare files.

```{r}
# list files
files = list.files("data/processed/data_preprocessed", full.names = TRUE)
```

## Load data and count by day

### Count by day

```{r read_preprocd_data}
# read data and bind into single dataframe
data = lapply(files, fread) |> rbindlist()

# assign day and count number of days
data[, date := date(
    as.POSIXct(time, origin = "1970-01-01", tz = "UTC")
)]
data_day_count = data[, list(.N), by = c("TAG_ID", "sp", "treat", "date")]
```

```{r hist_daily_counts}
ggplot(data_day_count)+
    geom_histogram(
        aes(N),
        fill = "grey"
    )+
    geom_vline(
        xintercept = 500
    )
```

### Filter IDs with fewer than 500 daily fixes

```{r filter_id_day}
# filter out days < 500 fixes
data_day_count = data_day_count[N > 500, ]

# join to data and remove data
data = merge(data, data_day_count)
```

### Write to file

The data are sufficiently small to be written to a single file.

```{r write_data}
# remove columns count and N
data = data[, !c("count", "N")]

# write data
fwrite(data, file = "data/processed/data_for_analysis.csv")
```
