---
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
library(sf)
library(ctmm)
```

```{r}
# load swallow data preprocessed
files = list.files(
  path = "data/processed/data_preprocessed",
  pattern = "Hirundo",
  full.names = TRUE
)
```

```{r}
# read all data
data = lapply(files, fread)

# bind list and split by id and date
data = rbindlist(data)
data = split(data, by = c("TAG", "date"))
```

```{r}
# prepare telemetry
data_tel = lapply(
  data, function(df) {
    # prepare and convert to telemetry object
    tel = df[, c("TAG", "X", "Y", "time")]
    # handle time
    tel[, time := as.POSIXct(
      time,
      tz = "Asia/Jerusalem",
      origin = "1970-01-01"
    )]
    
    # edit coordinates to long-lat for ctmm
    tel_sf = st_as_sf(
      tel,
      coords = c("X", "Y"), crs = 2039 
    )
    tel_sf = st_transform(
      tel_sf,
      crs = 4326
    )
    
    # change names for ctmm
    setnames(
      tel,
      c("individual.local.identifier", "location.long", "location.lat",
        "timestamp")
    )
    # get coordinates in long-lat
    tel_coords = st_coordinates(tel_sf)
    tel[, c("location.long", "location.lat") := list(
      tel_coords[, "X"],
      tel_coords[, "Y"]
    )]
    
    # make telemetry object
    tel = as.telemetry(tel)
    tel
  }
)
```

```{r}
# guess ctmm fits
ctmm_guess = lapply(data_tel, ctmm::ctmm.guess, interactive = FALSE)
# save
save(
  ctmm_guess,
  file = "data/results/data_ctmm_guess_swallows.Rds"
)

# select movement models
ctmm_fit = Map(
  data_tel, ctmm_guess,
  f = function(df, guess) {
    ctmm.select(df, guess, method = "pHREML", verbose = TRUE)
  }
)
# save fit data
save(
  ctmm_fit,
  file = "data/results/data_ctmm_fit_swallows.Rds"
)
```

```{r}
# utilisation distribution data
data_ud = Map(
  data_tel, ctmm_fit,
  f = function(df, fit) {
    akde(
      df, fit, weights = TRUE
    )
  }
)

# save fit data
save(
  data_ud,
  file = "data/results/data_ud_swallows.Rds"
)
```

## Summarise movement and utilisation

```{r}
library(data.table)
library(ggplot2)
library(colorspace)
```

```{r}
load("data/results/data_ctmm_fit_swallows.Rds")
load("data/results/data_ud_swallows.Rds")
```

```{r}
# get data
id = stringr::str_extract(names(ctmm_fit), "\\d{10}")
date = stringr::str_extract(names(ctmm_fit), "\\d{4}-\\d{2}-\\d{2}")
```

```{r}
# get movement model data
estimates = lapply(ctmm_fit, function(le) {
  est = as.data.frame(
    summary(
      le[[1]]
    )$CI
  ) |> 
    as.data.table(
      keep.rownames = "variable"
    )
  est = est[variable == "area (square kilometers)", variable := "area_ctmm"]
  est
})

# get wAKDE fitted utilisation distribution data
ud = lapply(data_ud, function(le) {
  est = as.data.frame(
    summary(le)$CI
  ) |> 
    as.data.table(
      keep.rownames = "variable"
    )
  
  est = est[variable == "area (square kilometers)", variable := "area_wakde"]
  est
})
```

```{r}
# bind rows and link to id and date
estimates = Map(
  estimates, ud, id, date,
  f = function(df1, df2, id, date) {
    df = rbindlist(
      list(df1, df2), use.names = TRUE
    )
    df$id = id
    df$date = date
    df
  }
)

estimates = rbindlist(estimates)

# save data
fwrite(
  estimates, 
  file = "data/results/data_ctmm_ud_swallows.csv"
)
```

## Link with RRV and moult status

```{r}
# read rrv
rrv = fread("data/results/data_daily_rrv.csv")
rrv$date = as.character(rrv$date)

estimates$id = as.integer(estimates$id)

data = merge(
  estimates,
  rrv,
  by.x = c("id", "date"),
  by.y = c("TAG", "date"),
  all.x = TRUE,
  all.y = FALSE
)
```

```{r}
# speed over rrv summary
psdf = data[variable == "speed (kilometers/day)"]
psdf2 = psdf[, list(
  rrv_mean = mean(rrv_calc),
  rrv_sd = sd(rrv_calc),
  speed_mean = mean(est),
  speed_low = mean(low),
  speed_high = mean(high),
  speed_sd = sd(est)
), by = c("treat")]
```

## Fit GAM movement to data

```{r}
library(mgcv)

mod1 = gam(
  est ~ s(rrv_calc, k = ),
  data = psdf
)

gratia::draw(mod1)
```


## Plot movement and utilisation over RRV

```{r}
ggplot(psdf2)+
  geom_jitter(
    data = psdf,
    aes(
      rrv_calc, est,
      col = treat
    ),
    shape = 1
  )+
  geom_linerange(
    aes(
      x = rrv_mean,
      ymin = speed_mean - speed_sd,
      ymax = speed_mean + speed_sd
    )
  )+
  geom_linerange(
    aes(
      x = rrv_mean,
      y = speed_mean,
      xmin = rrv_mean - rrv_sd,
      xmax = rrv_mean + rrv_sd
    )
  )+
  geom_point(
    aes(
      rrv_mean, speed_mean,
      fill = treat
    ),
    shape = 21,
    size = 3
  )+
  scale_fill_discrete_sequential(
    palette = "Batlow",
    l1 = 30, l2 = 60,
    breaks = c("NonMoulting", "Moulting", "Manipulated"),
    labels = c("N. Moulting", "Moulting", "Manipulated")
  )+
  scale_colour_discrete_sequential(
    palette = "Batlow",
    l1 = 50, l2 = 50,
    guide = "none"
  )+
  coord_cartesian(
    # ylim = c(0, NA)
  )+
  theme_test(
    base_size = 10,
    base_family = "Arial"
  )+
  theme(
    legend.position = "top",
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    )
  )+
  labs(
    x = "RRV (More ragged wing)",
    y = "Daily distance moved (km)",
    fill = NULL
  )
```

