---
editor_options: 
  chunk_output_type: console
---

# Cumulative daily distance

## Load libraries and prepare files

```{r}
# libs for data
library(data.table)
library(lubridate)

# library for atlas data
library(atlastools)

# plotting
library(ggplot2)
library(colorspace)
```

```{r}
# load data from file
data <- fread("data/processed/data_for_analysis.csv")
```

## Calculate distances and times of day

### Calculate distance

```{r}
# get distances bw points
data <- split(data, by = c("TAG_ID", "sp", "treat", "date"))

# order data by time
data <- lapply(data, setorderv, "time")

# calculate distances
data <- lapply(data, function(df) {
  df[, distance := atl_simple_dist(df)]
  df$distance <- nafill(df$distance, type = "const", fill = 0)
  df
})
```

### Calculate time of day

```{r}
# get interval since start of day --- will be nighttime
data <- lapply(data, function(df) {
  df[, posix_time := as.POSIXct(time, origin = "1970-01-01", tz = "UTC")]
  # difference in minutes between time and start of day
  df[, min_day := as.numeric(
      difftime(posix_time, 
        as_datetime(min(date(posix_time))), units = "mins")
  )]
  # round min_day to 10 mins
  df[, min_day := plyr::round_any(min_day, 10)]
})
```

## Cumulative daily distance

### Calculate cumulative daily distance

```{r}
# summarise distance in 10 min intervals and then cuml distance
data_summary = lapply(data, function(df) {
    # sum distance in interval
    df = df[, list(distance = sum(distance)), 
        by = c("min_day", "date", "sp", "treat", "TAG_ID")]
    df[, cuml_distance := cumsum(distance)]
    df
})

# bind the rows
data_summary <- rbindlist(data_summary)

# set levels
data_summary$treat = factor(data_summary$treat,
                            levels = c("NonMoulting", "Moulting", "Manipulated"))

# save to file
fwrite(data_summary, file = "data/results/data_daily_cumulative_distance.csv")
```

### Plot cumulative daily distance over time

```{r plot_cuml_dist}
# make labeller
label_condition = c(
  "NonMoulting" = "Non moulting",
  "Moulting" = "Moulting",
  "Manipulated" = "Manipulated"
)

ggplot(data_summary[sp != "Hirundo" & treat != "LongPeriod"]) +
  geom_path(
    aes(
      min_day, cuml_distance,
      group = interaction(TAG_ID, date),
      col = treat
    ),
    show.legend = F,
    alpha = 0.3
  )+
  scale_colour_discrete_qualitative(
    palette = "Harmonic",
    l1 = 50, h1 = 50,
    rev = T
  )+
  scale_y_sqrt(
    labels = function(x) { 
      scales::comma(x, accuracy = 1, scale = 0.001, suffix = "km")
    },
    breaks = c(1, 5, 10, 20) * 1e3
  )+
  scale_x_continuous(
    labels = function(x) { sprintf("%ihr", as.integer(x / 60)) },
    breaks = c(1, 6, 12, 18, 23) * 60
  )+
  coord_cartesian(
    expand = F,
    ylim = c(0, 30e3)
  )+
  theme_test()+
  theme(
    axis.text.x = element_text(
      size = 8
    )
  )+
  facet_grid(
    sp ~ treat, 
    labeller = labeller(
      treat = label_condition
    )
  )+
  labs(
    x = "Hour of day",
    y = "Cumulattive distance (km)"
  )

# save plot to file
ggsave(
  filename = "figures/fig_cumulative_daily_distance.png",
  height = 6, width = 6
)
```

## Total daily distance

### Calculate total daily distance

```{r tot_daily_dist}
# sum distances per day
data_dist_summary = rbindlist(data)
data_dist_summary = data_dist_summary[, list(
  total_distance = sum(distance)
), by = c("TAG_ID", "sp", "treat", "date")]

# check for as many rows as there are combinations of the identifiers
assertthat::assert_that(
  nrow(data_dist_summary) == length(data),
  msg = "incorrect number of total daily distances"
)

# set factor order
# set levels
data_dist_summary$treat = factor(data_dist_summary$treat,
                            levels = c("NonMoulting", "Moulting", "Manipulated"))
```

### Plot total daily distance

```{r}
# remove swallows and long term sparrows
data_dist_summary = data_dist_summary[sp != "Hirundo" & treat != "LongPeriod"]

# make plot
ggplot(data_dist_summary)+
  geom_jitter(
    aes(treat, total_distance),
    width = 0.1,
    col = "grey70",
    alpha = 0.5
  )+
  geom_boxplot(
    aes(
      treat, total_distance,
      col = treat
    ),
    outlier.shape = 1,
    show.legend = F,
    fill = alpha("grey", alpha = 0.3),
    width = 0.3
  )+
  scale_colour_discrete_qualitative(
    palette = "Harmonic",
    l1 = 50, h1 = 50,
    rev = T
  )+
  scale_y_sqrt(
    labels = function(x) { 
      scales::comma(x, accuracy = 1, scale = 0.001, suffix = "km")
    },
    breaks = c(1, 5, 10, 20) * 1e3
  )+
  scale_x_discrete(
    labels = c("Non moulting", "Moulting", "Manipulated")
  )+
  theme_test()+
  theme(
    axis.text.x = element_text(
      size = 8
    )
  )+
  facet_grid(~sp)+
  labs(
    x = "Wing condition",
    y = "Total distance (km)"
  )

# save as figure
ggsave(
  filename = "figures/fig_total_distance.png",
  height = 3, width = 6
)
```

