---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Compare SSF params with RRV

Here we compare SSF coefficients with RRV scores.

## Load libraries and prepare files

```{r}
# libs for data
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(stringr)

# libs for messages
library(glue)

# library for SSF data
library(amt)

# plotting libs
library(ggplot2)
library(colorspace)
```

Load data from saved `Rds` object, and RRV data.

```{r}
# add ssf data
load("data/results/data_fitted_ssfs.Rds")

# load rrv data
rrv = read_csv("data/results/data_daily_rrv.csv")
```

## SSF parameters

```{r}
# filter for bad fits
ssfs = filter(
  ssfs,
  !map_lgl(
    ssf, is.null
  )
)

# select track identifiers
ssf_params = select(
  ssfs,
  -matches("ssf")
)

# select model parameter for ndvi preference
ssf_params = mutate(
  ssf_params,
  coefs = map(ssfs$ssf, function(l) {
    tryCatch(
      expr = {
        broom::tidy(
          l$model
        )
      },
      error = function(e) {
        return(NULL)
      }
    )
  }),
  shape = map_dbl(ssfs$ssf, function(l) {
    l$sl_$params$shape
  })
)

# unnest
ssf_params = unnest(ssf_params, cols = coefs)
```

## Link SSF coefficients and RRV

```{r}
# make rrv date as date
rrv = mutate(
  rrv,
  date = lubridate::date(date)
)

# link ssf params and rrv
ssf_params = left_join(
  ssf_params,
  rrv
)
```

## Visualise coefficient NDVI and RRV

### Correct SL in LC classes

```{r}
# filter coefficients
data = filter(
  ssf_params,
  treat != "LongPeriod",
  !is.na(estimate),
  between(estimate, -50, 50)
)

# get sl coefficient for all models
data = data %>% 
  group_by(
    TAG_ID, date, sp, treat
  ) %>% 
  mutate(
    sl_coef = estimate[term == "sl_"]
  )

# get corrected SL for each landcover
data = ungroup(data)
data =
  mutate(
    data,
    estimate_corrected = case_when(
      str_detect(term, "sl_:landcover") ~ estimate + shape + sl_coef,
      str_detect(term, "sl_") ~ estimate + shape,
      TRUE ~ estimate
    )
  )


```

### Selection strength for landcover

```{r}
# select terms
data_lc_selection = data %>% 
  filter(
    !stringr::str_detect(term, "sl"),
    !stringr::str_detect(term, "(1)|(4)"),
    p.value <= 0.05
  )
# labels
lc_labels = c(
  "landcover1" = "Disturbed",
  "landcover2" = "Open",
  "landcover3" = "Vegetated",
  "landcover4" = "Water",
  "ndvi" = "NDVI"
)

# plot
fig_rss_lc = 
  ggplot(data_lc_selection)+
  geom_point(
    aes(
      rrv_calc, estimate_corrected,
      shape = sp
    )
  )+
  geom_smooth(
    aes(
      rrv_calc, estimate_corrected
    ),
    se = F,
    method = "glm"
  )+
  facet_wrap(
    ~term,
    labeller = labeller(
      term = lc_labels
    )
  )+
  theme(
    legend.position = "top"
  )+
  labs(
    x = "Calc. RRV",
    y = "Relative Selection Strength",
    shape = NULL
  )

# save figure
ggsave(
  fig_rss_lc,
  filename = "figures/fig_rss_lc_rrv.png"
); dev.off()
```


### Plot SL in LC classes over RRV

```{r}
# labels
sl_labels = c(
  "sl_" = "SL - settlement",
  "sl_:landcover1" = "SL - disturbed",
  "sl_:landcover2" = "SL - open",
  "sl_:landcover3" = "SL - vegetated",
  "sl_:landcover4" = "SL - water"
)

# plot
fig_sl_lc =
  ggplot(
  data = filter(data, p.value <= 0.05,
                # term != "sl_:landcover4",
                stringr::str_detect(term, "sl"))
  )+
  geom_point(
    aes(
      rrv_calc, estimate_corrected,
      shape = sp
    )
  )+
  geom_smooth(
    aes(
      rrv_calc, estimate_corrected
    ),
    se = F,
    method = "glm"
  )+
  facet_wrap(
    ~term, ncol = 5,
    labeller = labeller(
      term = sl_labels
    )
  )+
  theme(
    legend.position = "top"
  )+
  coord_cartesian(
    ylim = c(NA, 1.5)
  )+
  labs(
    x = "Calc. RRV",
    y = "Relative Selection Strength",
    col = "Species",
    shape = NULL
  )

# save figure
ggsave(
  fig_sl_lc,
  filename = "figures/fig_sl_lc_rrv.png"
); dev.off()
```

