---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(glue)
library(purrr)

library(amt)
```


```{r}
# read rrv
rrv = read_csv("data/results/data_daily_rrv.csv")
rrv$date = as.character(rrv$date)
```

## Fit clogit to data

```{r}
# read data
files = list.files(
  "data/processed/data_for_clogit",
  pattern = "csv", full.names = TRUE
)
```

```{r}
# which files
ids = stringr::str_extract(files, "\\d{10}")
dates = stringr::str_extract(files, "\\d{4}-\\d{2}-\\d{2}")
```

```{r}
to_keep = ids %in% rrv$TAG & dates %in% rrv$date
files = files[to_keep]
```

```{r}
# read data
data = map(
  files, read_csv
)
```

```{r}
# nest each dataframe by id and date
data = map(
  data, nest,
  steps = -c("id", "date")
)
```

```{r}
# prepare formula
ssf_formula <- glue(
  "case_ ~ vis_end + lc_end + vis_end:lc_end + \\
  strata(step_id_)"
)
```

```{r}
#### Prepare log file ####
# sink output to log
sink(file = "data/log_ssf_fit.log")

ssf_comment <- "Writing SSF log"

# first print date
print(
  glue("
    SSF fit log from {Sys.time()}

    comment: {ssf_comment}

  ")
)

#### SSF fittting ####
# fit model to all
data_ssf_fit = imap(
  data, function(.x, .y) {
    print(
      glue("working on row {.y}")
    )
    
    # pass through try catch and print to log
    tryCatch(
      
      # the model fitting expression to evaluate
      expr = {
        
        # print some information about the data -- which row, which id, treatment
        print(
          glue("id = {.x$id[1]}; \\
            date = {.x$date[1]}
            row in dataframe = {.y}
            formula = {ssf_formula}
            start time: {Sys.time()}
           ")
        )
        
        # fit a clogit function using amt
        ssf_fit = amt::fit_clogit(
          formula = as.formula(ssf_formula),
          data = .x$steps[[1]], # hardcoded as there is only 1 element
          method = "approximate"
        )
        
        # ssf coefs
        ssf_coefs = broom::tidy(
          ssf_fit$model
        )
        
        # print success message to the processing log
        print(
          glue("
            SUCCESS at time: {Sys.time()}
            ---

            ")
        )
        
        # return the model fit object
        ssf_coefs
      },
      error = function(e) {
        # print an error message with information about the data
        print(
          glue("FAILED at time: {Sys.time()}")
        )
        # print the error message itself
        print(e)
        
        # a trailing blank line
        print(
          glue("
            ---

            ")
        )
        
        # return null if there is an error
        NULL
      }
    )
  }
)

# end sinking to log
sink()
```

```{r}
# link with id and date data
# remove steps data
data_id = map_df(
  data, select, -steps
)

# add fit data as list
data_id = mutate(
  data_id,
  ssf_coefs = data_ssf_fit
)

# remove NULL elements indicating failed fits
# filter for bad fits
data_id <- filter(
  data_id,
  !map_lgl(
    ssf_coefs, is.null
  )
)

# unnest data
data_id = unnest(
  data_id,
  cols = ssf_coefs
)

# change date class
data_id = mutate(
  data_id,
  date = as.character(date)
)
```

## Link with rrv

```{r}
data_id = left_join(
  data_id,
  rrv,
  by = c("id" = "TAG", "date")
)

# save data
write_csv(
  data_id,
  file = "data/results/data_clogit_fits.csv"
)
```

## Remove data

```{r}
rm(data); gc()
```

## Plot clogit coefficients

```{r}
library(ggplot2)
```

```{r}
# remove non rrv data
ssf_coefs = data_id

ssf_coefs = filter(
  ssf_coefs,
  !is.na(rrv_calc)
)

# remove coefs where p > 0.05
# ssf_coefs = filter(
#   ssf_coefs,
#   p.value <= 0.05
# )
```

```{r}
ggplot(
  filter(
    ssf_coefs,
    sp == "Pycnonotus"
  )
)+
  geom_hline(
    yintercept = 0,
    col = 2,
    lty = 2
  )+
  geom_boxplot(
    aes(
      treat, estimate,
      col = treat
    )
  )+
  scale_y_continuous(
    # trans = ggallin::pseudolog10_trans
  )+
  facet_wrap(
    ~term,
    scales = "free_y"
  )
```

```{r}
ggplot(
  filter(
    ssf_coefs,
    sp == "Pycnonotus"
  )
)+
  geom_hline(
    yintercept = 0,
    lty = 2
  )+
  geom_point(
    aes(
      rrv_calc, estimate,
      col = treat
    ),
    shape = 1,
    size = 3
  )+
  geom_smooth(
    aes(
      rrv_calc, estimate,
      col = treat
    ),
    method = "glm"
  )+
  scale_x_reverse()+
  scale_y_continuous(
    # trans = ggallin::pseudolog10_trans
  )+
  facet_wrap(
    ~term,
    scales = "free_y"
  )
```
