---
editor_options: 
  chunk_output_type: console
---

# Prepare covariate layers

```{r}
library(amt)
library(purrr)
library(data.table)
```

## Prepare extent from SSA data

```{r}
load("data/processed/data_for_ssf.Rds")
```

Get step coordinates and make mask layer for raster covariates.

```{r}
# get unique coords of real and potential steps
coordinates = lapply(
  tracks$data, function(df) {
    coords = tibble(
      x = c(df$x1_, df$x2_),
      y = c(df$y1_, df$y2_)
    ) |>
      distinct()
  }
)

# get unique coords across birds
coordinates = bind_rows(coordinates) %>% 
  distinct()

# make convex hull
mcp = st_as_sf(
  coordinates,
  coords = c("x", "y"),
  crs = 2039
) %>% 
  st_union() %>% 
  st_convex_hull()

# save mcp
st_write(
  mcp,
  dsn = "data/spatial/data_tracking_mcp.gpkg",
  layer = "mcp_tracking"
)

rm(coordinates, tracks)
gc()
```

## Prepare extent from residence patch data

```{r}
res_patch_spatial = st_read("data/spatial/data_patch_spatials.gpkg")
rp_sf_mcp = st_union(res_patch_spatial) %>% 
  st_convex_hull()

# save
st_write(
  rp_sf_mcp,
  dsn = "data/spatial/data_res_patch_mcp.gpkg",
  layer = "mcp_tracking"
)
```

## Load total mcp

```{r}
rp_mcp = st_read("data/spatial/data_res_patch_mcp.gpkg") %>% 
  `st_crs<-`(2039)
ssf_mcp = st_read("data/spatial/data_tracking_mcp.gpkg") %>% 
  `st_crs<-`(2039)

# union and get mask
combined_mcp = st_union(
  rp_mcp, ssf_mcp
)

# the ssf mcp is sufficient as it is larger
st_write(
  combined_mcp,
  dsn = "data/spatial/mask_cov_layers.shp"
)
```

## Load covariate layers

Cov layers are not large enough.
