---
editor_options: 
  chunk_output_type: console
---

```{r}
library(readr)
library(purrr)
library(dplyr)
library(tidyr)

library(ggplot2)
library(colorspace)
library(patchwork)
```

```{r}
# read rrv
rrv = read_csv("data/results/data_daily_rrv.csv")
rrv$date = as.character(rrv$date)
```

## Fit clogit to data

```{r}
# read data
files = list.files(
  "data/processed/data_for_clogit",
  pattern = "csv", full.names = TRUE
)
```

```{r}
# which files
ids = stringr::str_extract(files, "\\d{10}")
dates = stringr::str_extract(files, "\\d{4}-\\d{2}-\\d{2}")
```

```{r}
to_keep = ids %in% rrv$TAG & dates %in% rrv$date
files = files[to_keep]
```

```{r eval=FALSE, include=FALSE}
# read data
data = map(
  files, read_csv
)

# bind and save
data = bind_rows(data)

# step means
data_step_covs = group_by(
  data,
  id, date,
  patch_start,
  patch_end,
  case_,
) %>% 
  summarise(
    across(
      matches(c("ndvi", "vis")),
      mean
    )
  )

# proportion of lc class
data_step_lc = group_by(
  data,
  id, date,
  patch_start,
  patch_end,
  case_,
) %>%
  summarise(
    as.data.frame(table(lc_end))
  )

# convert to percentages
data_step_lc = ungroup(
  data_step_lc
) %>% 
  group_by(
    id, date, patch_start, patch_end, case_
  ) %>% 
  mutate(
    Freq = Freq / sum(Freq)
  )

# pivot wide
data_step_lc = pivot_wider(
  data_step_lc,
  names_from = "lc_end",
  values_from = "Freq", 
  values_fill = 0
)

# link to env attributes
data_step_covs = left_join(
  data_step_covs,
  data_step_lc
)

write_csv(
  data_step_covs,
  file = "data/results/data_ssf_step_covs.csv"
)
```

```{r}
rm(data); gc()
```

## Link with rrv and treatment

```{r}
# read in saved data
data_step_covs = read_csv("data/results/data_ssf_step_covs.csv")
# read rrv
rrv = read_csv("data/results/data_daily_rrv.csv")
rrv$date = as.character(rrv$date)
```

```{r}
data_step_covs = mutate(
  data_step_covs,
  date = as.character(date)
)

data_step_covs = left_join(
  data_step_covs,
  rrv,
  by = c("id" = "TAG", "date")
)
```

### Summarise by case and treatment

```{r}
# filter for high ndvi values
data_sel = filter(
  data_step_covs,
  between(ndvi_mean_end, 0.4, 1)
)

# filter out data without species or rrv
data_sel = filter(
  data_sel,
  !is.na(sp),
  !is.na(treat),
  !is.na(rrv_calc)
)

# summarise
sdf = group_by(
  data_sel,
  sp, treat, case_
) |> 
  summarise(
    across(
      c(rrv_calc, vis_mean_end, ndvi_mean_end),
      .fns = list(
        mean = function(x) mean(x, na.rm = T),
        sd = function(x) sd(x, na.rm = T)
      )
    )
  ) |> 
  rename(
    vis_mean = vis_mean_end_mean,
    vis_sd = vis_mean_end_sd,
    ndvi_mean = ndvi_mean_end_mean,
    ndvi_sd = ndvi_mean_end_sd
  ) |> 
  mutate(
    case_ = if_else(case_, "real", "alternate")
  )
```

### Model visibility with RRV

```{r}
# convert sp and treat to factor
data_sel = mutate(
  data_sel,
  across(
    c(sp, treat, id),
    .fns = as.factor
  )
)
```

```{r}
library(mgcv)

mod1 = gam(
  vis_mean_end ~ s(rrv_calc, by = sp, k = 3) +
    s(sp, bs = "re"),
  data = filter(
    data_sel, case_
  )
)

summary(mod1)
gratia::draw(mod1)
```

```{r}
# make prediction table
pred_data = crossing(
  sp = as.factor(unique(data_sel$sp)),
  id = "new",
  treat = as.factor(unique(data_sel$treat)),
  rrv_calc = seq(0, 20, 0.5)
)

# filter for unrealistic
pred_data = filter(pred_data,
  (treat == "NonMoulting" & rrv_calc == 0) |
  (treat == "Moulting" & between(rrv_calc, 2, 12)) |
  (treat == "Manipulated" & between(rrv_calc, 12, 20))
)

# get prediction
pred = predict(mod1, newdata = pred_data, allow.new.levels = T, se.fit = T)

pred_data$pred = pred$fit
pred_data$se = pred$se.fit

# explore
ggplot(data_sel)+
  # geom_jitter(
  #   aes(
  #     rrv_calc, vis_mean_end,
  #     col = treat
  #   ),
  #   shape = 1
  # )+
  geom_point(
    data = pred_data,
    aes(
      rrv_calc, pred
    )
  )+
  facet_grid(
    ~sp
  )
```


### Plot figure 2

```{r}
fig_vis_selection = 
ggplot(sdf)+
  geom_jitter(
    data = filter(
      data_sel,
      case_
    ),
    aes(
      rrv_calc, vis_mean_end,
      col = treat,
    ),
    shape = 1,
    size = 0.3
  )+
  geom_ribbon(
    data = filter(
      pred_data,
      !(sp %in% c("Passer", "Pycnonotus") & rrv_calc > 17)
    ),
    aes(
      rrv_calc,
      ymin = pred - se,
      ymax = pred + se
    ),
    fill = "transparent",
    col = "grey",
    lty = 1
  )+
  geom_line(
    data = filter(
      pred_data,
      !(sp %in% c("Passer", "Pycnonotus") & rrv_calc > 17)
    ),
    aes(
      rrv_calc, pred
    ),
    col = "indianred"
  )+
  geom_linerange(
    aes(
      x = rrv_calc_mean,
      ymin = vis_mean - vis_sd,
      ymax = vis_mean + vis_sd
    ),
    position = position_nudge(
      x = c(-1, 1)
    )
  )+
  geom_linerange(
    aes(
      x = rrv_calc_mean, y = vis_mean,
      xmin = rrv_calc_mean - rrv_calc_sd,
      xmax = rrv_calc_mean + rrv_calc_sd
    ),
    position = position_nudge(
      x = c(-1, 1)
    )
  )+
  geom_point(
    aes(
      rrv_calc_mean, vis_mean,
      shape = case_,
      fill = treat
    ),
    size = 3,
    position = position_nudge(
      x = c(-1, 1)
    )
  )+
  geom_text(
    data = tibble(
      x = 0,
      y = 0.9,
      l = "NDVI > 0.4"
    ),
    hjust = "inward",
    fontface = "italic",
    aes(x, y, label = l)
  )+
  scale_fill_discrete_sequential(
    palette = "Batlow",
    l1 = 30, l2 = 60,
    breaks = c("NonMoulting", "Moulting", "Manipulated"),
    labels = c("N. Moulting", "Moulting", "Manipulated")
  )+
  scale_colour_discrete_sequential(
    palette = "Batlow",
    l1 = 50, l2 = 50,
    guide = "none"
  )+
  scale_shape_manual(
    values = c(
      "real" = 21, 
      "alternate" = 25
    ),
    limits = c("alternate", "real"),
    # breaks = c("real", "alternate"),
    labels = c("Potential", "Real")
  )+
  facet_grid(
    cols = vars(sp),
    scales = "free_x"
  )+
  theme_test(
    base_size = 10,
    base_family = "Arial"
  )+
  theme(
    legend.position = "top",
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    )
  )+
  labs(
    x = "RRV (More ragged wing)",
    y = "Visibility at next patch",
    fill = NULL,
    shape = NULL
  )+
  guides(
    fill = guide_legend(
      override.aes = list(
        shape = 22
      )
    ),
    shape = guide_legend(
      override.aes = list(
        size = 3
      )
    )
  )

ggsave(
  fig_vis_selection,
  filename = "figures/fig_02.png",
  height = 87,
  width = 178,
  units = "mm"
)
```
