# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_mean_filter <- function(x_vec, t_vec, k) {
    .Call('_holeybirds_weighted_mean_filter', PACKAGE = 'holeybirds', x_vec, t_vec, k)
}

